### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by mithileshkarnati**
Sir,
I have added a Sample.java file to show a small small sample of how my account.java file works.
I am not completely done with it but i just want to know whether Im going in the right direction .

### CODE REVIEW

**Comment by gvagenas** [comment]
Hi @mithileshkarnati. You have done great work so far and here are my comments to move forward the project.
- Project should be a maven project. Check here for a quick guid https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html. Use same groupId as the Restcomm-Connect project (`org.restcomm`). For artifactId use `restcomm-connect.java.sdk`.
- For Java package name use `org.restcomm.connect.java.sdk` and then follow the application structure, for example `org.restcomm.connect.java.sdk.http`
- Provide documentation using Asciidoc, check how we do it for Restcomm-Connect.
- Provide junit test cases. The project should be well covered by junit testes. Unit tests is the best documentation. 

Let me know if you need any help
George

**Review by gvagenas — CHANGES_REQUESTED** [review]
Hi @mithileshkarnati. You have done great work so far and here are my comments to move forward the project.

- Project should be a maven project. Check here for a quick guid https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html. Use same groupId as the Restcomm-Connect project (org.restcomm). For artifactId use restcomm-connect.java.sdk.
- For Java package name use org.restcomm.connect.java.sdk and then follow the application structure, for example org.restcomm.connect.java.sdk.http
- Provide documentation using Asciidoc, check how we do it for Restcomm-Connect.
- Provide junit test cases. The project should be well covered by junit testes. Unit tests is the best documentation.

Let me know if you need any help
George

**Comment by gvagenas** [comment]
Also make sure that the documentation will also contain instructions for how to use the SDK (since this will be a maven project, to use the SDK one should declare the maven dependency in their project)

**Comment by gvagenas** [comment]
Also, important is to include LICENSE header on all files, and the LICENSE file at the root of the project. 
```
/*
 * TeleStax, Open Source Cloud Communications
 * Copyright 2011-2016, Telestax Inc and individual contributors
 * by the @authors tag.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
```
* Eclipse: 
Preferences -> Java -> Code Style -> Code Templates -> Comments -> Files -> Pattern
* Intellij Idea
Settings -> Editor -> Copyright and Copyright profiles

**Comment by scottbarstow** [comment]
@gvagenas I reviewed this initial PR and it appears we're using the XML endpoints rather than the JSON endpoints for the API. Was that on purpose?

**Comment by gvagenas** [comment]
@scottbarstow I missed that point since I first check for the structural and basic settings of the project.
I believe we should support JSON endpoints

**Pull request closed without merging**
