### PR TITLE
Branch accounts,application

### PR DESCRIPTION
**Pull request by mithileshkarnati**
I have added Accounts and Applications Modules
Only thing missing is AsciiDocs

### CODE REVIEW

**Comment by mithileshkarnati** [comment]
I have also added ASCII Documentation for the Accounts module

**Comment by gvagenas** [comment]
Great job @mithileshkarnati . Only one issue, please provide proper package name for the classes in the test folder.
PR is ready to merge after this minor fix.

Also please, create issues for the missing parts. Next PRs will have to be tied to the issue it will resolve.

**Comment by gvagenas** [comment]
Also provide README.md with the following:

- Give a short description of the project (1-2 lines)
- how to build the project
- how to run the tests
- Java version supported
- Reference any dependencies that might be needed to be added by a developer
- Provide instructions for where to download Restcomm and point to the restcomm documentation site
- Provide information how and where developers can open issues and feature requests

Also please provide example application and instructions for how to run it etc.

Imagine you have a Java developer but not familiar with Restcomm-Connect, that wants to use the library. Given that, we must provide any necessary information for him to get started.

**Comment by gvagenas** [comment]
Congrats @mithileshkarnati PR merged, great job 👍 
Looking forward for the rest of the work

**Pull request merged**
